name: Link Checker Workflow

on: [push]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}
          separator: '\n'

      - name: Wait on federalist build
        id: wait-federalist-build
        if: steps.changed-files.outputs.added_files != ''
        uses: cloud-gov/wait-federalist-build-action@main
        with:
          debug: true
          commit-sha: ${{ github.event.pull_request.head.sha }}

      - name: Build website using branch-specific configuration
        if: steps.changed-files.outputs.added_files != ''
        run: |
          CI_CONFIG_FILE="_config_ci.yml"
          PREVIEW_URL=${{ steps.wait-federalist-build.outputs.preview-url }}
          # strip trailing slash to make link checking work properly
          echo "url: ${PREVIEW_URL%/}" > $CI_CONFIG_FILE
          echo "github_branch: ${{ github.event.pull_request.head.ref }}" >> $CI_CONFIG_FILE
          npm run build -- --config _config.yml,$CI_CONFIG_FILE
      - name: Build website with normal configuration
        if: steps.changed-files.outputs.added_files == ''
        run: npm run build

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: --github-token ${{secrets.GITHUB_TOKEN}} --max-concurrency 64 --verbose --no-progress './*.md' './_site/**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
